ALTER TABLE "AIProviders" ADD COLUMN IF NOT EXISTS "lastError" TEXT;
ALTER TABLE "AIProviders" ADD COLUMN IF NOT EXISTS "lastChecked" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "AIProviders" ADD COLUMN IF NOT EXISTS "latency" INTEGER;
